"use client";

import { useState, useRef, useEffect } from "react";
import { Card, PageHeader, Badge } from "@/components/ui/Card";
import { Bot, Send, Sparkles, User, Lightbulb } from "lucide-react";

interface Message {
  id: string;
  role: "user" | "assistant";
  content: string;
  timestamp: Date;
}

const suggestions = [
  "What is my leave balance?",
  "Show my attendance this month",
  "Who is on leave today?",
  "Explain the leave policy",
  "What are the salary components?",
  "How does performance review work?",
  "What benefits do I have?",
  "Show attrition risk report",
];

// Simulated AI responses
const getAIResponse = (message: string): string => {
  const q = message.toLowerCase();
  if (q.includes("leave balance") || q.includes("my leave"))
    return "📋 **Your Leave Balances (2026)**\n\n• Casual Leave: 8/12 remaining\n• Sick Leave: 8/10 remaining\n• Earned Leave: 12/15 remaining\n\nYou have 28 total leaves remaining. Would you like to apply for leave?";
  if (q.includes("attendance") || q.includes("my hours"))
    return "⏰ **Your Attendance This Month**\n\n• Days present: 18/20 working days\n• Average hours: 8.4 hrs/day\n• Late arrivals: 1\n• WFH days: 3\n\nYour attendance rate is 96% — above team average!";
  if (q.includes("on leave today") || q.includes("who is"))
    return "🏖️ **Employees on Leave Today**\n\n• Sneha Joshi (Design) — Earned Leave\n• Kavya Reddy (Analytics) — Casual Leave\n\n2 employees are on leave. 166 are active today.";
  if (q.includes("leave policy"))
    return "📜 **Leave Policy Summary**\n\n• Casual Leave: 12 days/year\n• Sick Leave: 10 days/year\n• Earned Leave: 15 days/year\n• Maternity: 26 weeks\n• Paternity: 2 weeks\n\nLeaves require manager approval. Max 5 earned leaves carry forward. Apply via the Leave module.";
  if (q.includes("salary") || q.includes("component") || q.includes("payroll"))
    return "💰 **Salary Structure**\n\n• Basic Pay: 40% of CTC\n• HRA: 40% of Basic\n• DA: 10% of Basic\n• Special Allowance: 15% of Basic\n\n**Deductions:**\n• PF: 12% of Basic\n• ESI: 0.75% (if applicable)\n• TDS: As per slab\n\nPayslips are generated by the 1st of each month.";
  if (q.includes("performance") || q.includes("review"))
    return "🎯 **Performance Review Process**\n\n1. **Quarterly Check-ins** — Informal progress review\n2. **Self Assessment** — Rate yourself on key competencies\n3. **Manager Review** — Manager evaluates and calibrates\n4. **Final Rating** — 1-5 scale\n\nCurrent cycle: Annual 2026 (Due: December)\nYour last rating: 4.2/5 ⭐";
  if (q.includes("benefit"))
    return "🏥 **Your Benefits Package**\n\n• Health Insurance: ₹5L family floater\n• Dental: ₹25K/year\n• Gym Allowance: ₹1,500/month\n• Meal Vouchers: ₹2,200/month (tax-free)\n• Education: ₹50K/year reimbursement\n• WFH Allowance: ₹5K/month";
  if (q.includes("attrition") || q.includes("risk"))
    return "⚠️ **Attrition Risk Report**\n\n**High Risk:**\n• Vikram Patel (Engineering) — 76% risk\n• Sneha Joshi (Design) — 62% risk\n• Amit Roy (Engineering) — 54% risk\n\n**Recommendations:**\n• Schedule retention conversations\n• Review compensation benchmarks\n• Consider role enrichment opportunities";
  return "I can help with questions about leave policy, attendance, payroll, performance reviews, benefits, training, holidays, and more. Try asking about a specific topic! 🤖";
};

export default function AIAssistantPage() {
  const [messages, setMessages] = useState<Message[]>([
    { id: "1", role: "assistant", content: "Hello! 👋 I'm your AI HR Assistant. I can help you with leave policies, attendance, payroll, benefits, performance reviews, and more. What would you like to know?", timestamp: new Date() },
  ]);
  const [input, setInput] = useState("");
  const [isTyping, setIsTyping] = useState(false);
  const messagesEnd = useRef<HTMLDivElement>(null);

  useEffect(() => {
    messagesEnd.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages]);

  const sendMessage = (text: string) => {
    if (!text.trim()) return;
    const userMsg: Message = { id: Date.now().toString(), role: "user", content: text, timestamp: new Date() };
    setMessages((prev) => [...prev, userMsg]);
    setInput("");
    setIsTyping(true);

    setTimeout(() => {
      const response = getAIResponse(text);
      const botMsg: Message = { id: (Date.now() + 1).toString(), role: "assistant", content: response, timestamp: new Date() };
      setMessages((prev) => [...prev, botMsg]);
      setIsTyping(false);
    }, 800 + Math.random() * 700);
  };

  return (
    <div className="animate-fade-in h-[calc(100vh-7rem)] flex flex-col">
      <PageHeader title="AI Assistant" subtitle="Ask anything about HR policies & your data" />

      <div className="flex-1 flex gap-4 min-h-0">
        {/* Chat area */}
        <div className="flex-1 flex flex-col glass-card overflow-hidden">
          {/* Messages */}
          <div className="flex-1 overflow-y-auto p-4 space-y-4">
            {messages.map((msg) => (
              <div key={msg.id} className={`flex gap-3 ${msg.role === "user" ? "justify-end" : ""}`}>
                {msg.role === "assistant" && (
                  <div className="w-8 h-8 rounded-xl flex items-center justify-center shrink-0" style={{ background: "linear-gradient(135deg, #6C5CE7, #00CEC9)" }}>
                    <Bot className="w-4 h-4 text-white" />
                  </div>
                )}
                <div className={`max-w-[75%] p-3 rounded-2xl text-sm leading-relaxed ${
                  msg.role === "user" ? "bg-purple-500/20 text-white rounded-tr-md" : "text-slate-300 rounded-tl-md"
                }`} style={msg.role === "assistant" ? { background: "rgba(255,255,255,0.04)" } : {}}>
                  <div className="whitespace-pre-wrap">{msg.content}</div>
                  <p className="text-[10px] text-slate-600 mt-1">{msg.timestamp.toLocaleTimeString("en-US", { hour: "2-digit", minute: "2-digit" })}</p>
                </div>
                {msg.role === "user" && (
                  <div className="w-8 h-8 rounded-xl flex items-center justify-center shrink-0" style={{ background: "linear-gradient(135deg, #FD79A8, #6C5CE7)" }}>
                    <User className="w-4 h-4 text-white" />
                  </div>
                )}
              </div>
            ))}
            {isTyping && (
              <div className="flex gap-3">
                <div className="w-8 h-8 rounded-xl flex items-center justify-center shrink-0" style={{ background: "linear-gradient(135deg, #6C5CE7, #00CEC9)" }}>
                  <Bot className="w-4 h-4 text-white" />
                </div>
                <div className="p-3 rounded-2xl rounded-tl-md" style={{ background: "rgba(255,255,255,0.04)" }}>
                  <div className="flex gap-1">
                    <span className="w-2 h-2 rounded-full bg-purple-400 animate-pulse" />
                    <span className="w-2 h-2 rounded-full bg-purple-400 animate-pulse" style={{ animationDelay: "0.2s" }} />
                    <span className="w-2 h-2 rounded-full bg-purple-400 animate-pulse" style={{ animationDelay: "0.4s" }} />
                  </div>
                </div>
              </div>
            )}
            <div ref={messagesEnd} />
          </div>

          {/* Input */}
          <div className="p-4 border-t border-white/[0.06]">
            <div className="flex gap-2">
              <input type="text" value={input} onChange={(e) => setInput(e.target.value)}
                     onKeyDown={(e) => e.key === "Enter" && sendMessage(input)}
                     placeholder="Ask me anything about HR..." className="input-dark flex-1" />
              <button onClick={() => sendMessage(input)} disabled={!input.trim()}
                      className="btn-primary px-4 disabled:opacity-40">
                <Send className="w-4 h-4" />
              </button>
            </div>
          </div>
        </div>

        {/* Suggestions sidebar */}
        <div className="w-64 hidden xl:block">
          <Card>
            <div className="flex items-center gap-2 mb-3">
              <Lightbulb className="w-4 h-4 text-yellow-400" />
              <h3 className="text-sm font-semibold text-white">Try asking</h3>
            </div>
            <div className="space-y-2">
              {suggestions.map((s, i) => (
                <button key={i} onClick={() => sendMessage(s)}
                        className="w-full text-left p-2.5 rounded-xl text-xs text-slate-400 hover:text-white hover:bg-purple-500/10 border border-white/[0.06] hover:border-purple-500/20 transition-all">
                  {s}
                </button>
              ))}
            </div>
          </Card>

          <Card className="mt-4">
            <div className="flex items-center gap-2 mb-2">
              <Sparkles className="w-4 h-4 text-purple-400" />
              <h3 className="text-xs font-semibold text-white">AI Capabilities</h3>
            </div>
            <div className="space-y-1.5 text-[11px] text-slate-500">
              <p>• HR policy questions</p>
              <p>• Leave balance lookups</p>
              <p>• Attendance summaries</p>
              <p>• Attrition risk reports</p>
              <p>• Benefits information</p>
              <p>• Payroll breakdowns</p>
            </div>
          </Card>
        </div>
      </div>
    </div>
  );
}
